### ISSUE TITLE
get_data_generator is using too much GPU memory

### ISSUE THREAD

**Issue by andyshuo** [waymo-research/waymax#55]
Hi, 

I am having a issue of OOM for my GPU.

I looked into it and I realize get_data_generator() in dataloader.dataloader_utils is using around 36GB of GPU memory.
I loaded my policy model in another GPU.
I am using the dm_env_wrapper.

However, when the code runs env.reset(), it calls the get_data_generator() again, and I receive this error: 

`jaxlib.xla_extension.XlaRuntimeError: INVALID_ARGUMENT: Disallowed host-to-device transfer: aval=ShapedArray(float32[30000,3]), dst_sharding=GSPMDSharding({replicated})`

I looked up online, couldn't find the problem. 
I am guessing this is because of OOM. 

I once tried to build both training and validation envs at the same time.
I got the same error when I called act_spec() on validation env with absolute same code as training env. 
That's is the reason why I guessed it is causing because OOM.

Is it possible for me to run the env on CPU?
Or, is there anyway to reduce GPU memory usage?
Or, is there a problem with my code for using that much GPU memory?
Or, is there a way to solve the error above?

Thanks a lot!!!

**Comment by andyshuo** [comment]
Just solved the problem.
Since I was working with another GitHub code with transfer_guard set to disallow and it just failed. 

I set to allow and the problem is solved.
